### ISSUE TITLE
Still doesn't boot with this

### ISSUE THREAD

**Issue by HexagonWin** [jacklukem/BigSurfixes#12]
Device : MacBook Early 2008 (4,1)
Target macOS : 11.4 Big Sur

Hello, I'm trying to make Big Sur run in this MacBook4,1. When I use OCLP, the whole ~~usb things doesn't work, so I had to make my internal sata drive an installer drive in order to boot to the installer. And even after booting, all things usb related didn't work. (Reason for sata internal drive booting is because usb booting also give error, it gives Still waiting for root volume in verbose and show the disabled warning sign)
I then found the legacy usb installer fix in here. I made a clean usb again with oclp, and ran `BigSur BaseSystem legacy usb fix.command` and disconnected usb, and reconnected and ran `BigSur BaseSystem legacy usb fix2.command` in my Mojave hackintosh computer.
However, when I booted with this usb, the same waiting for boot volume error occured.

What will be the problem?? Thanks.

**Comment by jacklukem** [comment]
The unbootable BigSur environment is due to the too legacy USB host controller on that Mac, when you use an internal sata it's used only the AHCI kext and any USB host is ignored that's why you can boot the environment but of course without responsive USB devices.

Currently my BigSurFixes don't support MacBook4,1 , but you could try this: https://forums.macrumors.com/threads/macos-11-big-sur-on-unsupported-macs-thread.2242172/post-29315114
just restore the BigSurBaseSystemfix to an empty USB drive and check if you can boot the installer (maybe try also on a target internal SATA partition)

or maybe try also this my customised OC setup (useful for DDR2 RAM Mac): https://github.com/jacklukem/USBOpenCoreAPFSloader/releases/download/4.5/USBOpenCoreAPFSloader3b2.app.zip

**Comment by HexagonWin** [comment]
Thank you. Now I tried that BigSurBaseSystemfix.dmg to my drive, and applied OCLP. I'm still getting the `Still waiting for boot volume` and the Banned sign. Thanks. Should I use no OCLP?
Edit. No oclp and just doing it also gives error.

**Comment by HexagonWin** [comment]
I installed the BigSurBaseSystemfix.dmg and OCLP to my internal sata drive, it boots and as I expected USB mouse and keyboard doesn't work. (Light doesn't even turn on)
How would I try the "customised OC setup"? Thanks

**Comment by HexagonWin** [comment]
RMC Patcher, which worked for catalina had usb also working. Can I fetch kexts from it and put it onto BigSurfixes?

**Comment by jacklukem** [comment]
BigSurBaseSystemfix without OC directly from apple startup manager already embeds many legacy USB kext, but for that MacBook4,1 probably are required more kext, you can't easy swap them on BigSurfixes, because you need first to make a valid prelinkedkernel from a full Big Sur beta, then should add those extra USB kext to the BaseSystem modified for UUID matching.

**Comment by HexagonWin** [comment]
Oh.. okay.. But can't I just add more kexts by OC and just leave BSBSFix as it is?.. if it doesn't require changing kexts and instead only requires to install more kexts..

**Comment by jacklukem** [comment]
You could try here are the required kext: https://forums.macrumors.com/threads/macos-10-14-mojave-on-unsupported-macs-thread.2121473/post-27337044

Maybe I also could attempt to fix that on BigSurFixes, the only issue is that I don't have the target machine and I guess it's required to prelink correctly those many legacy USB kext.

**Comment by jacklukem** [comment]
here some working attempts to allow MacBook4,1 USB input devices (and kmutil) on a BigSur BaseSystem: https://forums.macrumors.com/threads/macos-11-big-sur-on-unsupported-macs-thread.2242172/post-30074402

and here some patched prelinkedkernels: https://github.com/jacklukem/BigSurfixes/tree/master/macbook41

**Comment by jacklukem** [comment]
Could you try, after restore this https://www.dropbox.com/s/p0c696odv0mujw8/bigsurbasesystemfix.dmg?dl=0

to an empty USB drive minimum 2 GB

`open /Volumes/BigSurBaseSystemfix/System/Library/PrelinkedKernels/`

 replacing with this: https://github.com/jacklukem/BigSurfixes/blob/master/macbook41/prelinkedkernelMB41_BT_GMAX3100.zip

or even this: https://github.com/jacklukem/BigSurfixes/blob/master/macbook41/prelinkedkernelMB41noLUSBi.zip

then while it works from apple startup manager, try also using as BigSurBaseSystemfix bootloader this:
https://github.com/jacklukem/USBOpenCoreAPFSloader/releases/download/4.5/USBOpenCoreAPFSloader3b2.app.zip

**Comment by jacklukem** [comment]
You might consider also to make a full BigSurBaseSystemfix installer for MacBook4,1 through this method:

https://github.com/jacklukem/BigSurfixes/issues/11#issuecomment-824785599

but on MacBook4,1 you could only install on internal SATA disk

another update:
https://forums.macrumors.com/threads/macos-11-big-sur-on-unsupported-macs-thread.2242172/post-30079972
