### ISSUE TITLE
Macbook not booting after install.

### ISSUE THREAD

**Issue by adog9712** [jacklukem/BigSurfixes#2]
Hi,

After successfully installing macOS Big Sur on my Macbook5,2 which has as Penryn processor. It then won’t boot to Big Sur. I get a flashing image of a folder with a question mark in. 

Please help. 
Many thanks
adog9712

**Comment by jacklukem** [comment]
Your MacBook5,2 not only is Penryn but also a non-APFS with legacy USB, which method do you used to install ?

Because I made many different method for group of machines.

You should use this method: https://forums.macrumors.com/threads/macos-11-big-sur-on-unsupported-macs-thread.2242172/post-28737950

Anyway at apple startup manager, to skip the "question mark folder" try this bootloader: https://github.com/jacklukem/USBOpenCoreAPFSloader/releases/download/3.1/USBOpenCoreAPFSloader3b.app.zip

making it with the option "Near an USB device without erasing" and selecting the USB BigSur Installer label as target, or you could use an empty USB drive, then plug it, hold alt-option key after power-on, and select your BigSur label or "macOS Installer" maybe needs to complete the stage3 installer.

**Comment by jacklukem** [comment]
Your MacBook5,2 not only is Penryn but also a non-APFS with legacy USB, which method do you used to install ?

Because I made many different method for group of machines.

Anyway at apple startup manager, to skip the "question mark folder" try this: https://github.com/jacklukem/USBOpenCoreAPFSloader/releases/download/3.1/USBOpenCoreAPFSloader3b.app.zip

making it with the option "Near an USB device without erasing" and selecting the USB BigSur Installer label as target, or you could use an empty USB drive, then plug it, hold alt-option key after power-on, and select your BigSur label or "macOS Installer" maybe needs to complete the stage3 installer.

**Comment by jacklukem** [comment]
Your MacBook5,2 not only is Penryn but also a non-APFS with legacy USB, which method do you used to install ?

Because I made many different method for group of machines.

Anyway at apple startup manager, to skip the "question mark folder" try this: https://github.com/jacklukem/USBOpenCoreAPFSloader/releases/download/3.1/USBOpenCoreAPFSloader3b.app.zip

making it with the option "Near an USB device without erasing" and selecting the USB BigSur Installer label as target, or you could use an empty USB drive, then plug it, hold alt-option key after power-on, and select your BigSur label or "macOS Installer" maybe needs to complete the stage3 installer.

**Comment by jacklukem** [comment]
Your MacBook5,2 not only is Penryn but also a non-APFS with legacy USB, which method do you used to install ?

Because I made many different method for group of machines.

Anyway at apple startup manager, to skip the "question mark folder" try this: https://github.com/jacklukem/USBOpenCoreAPFSloader/releases/download/3.1/USBOpenCoreAPFSloader3b.app.zip

making it with the option "Near an USB device without erasing" and selecting the USB BigSur Installer label as target, or you could use an empty USB drive, then plug it, hold alt-option key after power-on, and select your BigSur label or "macOS Installer" maybe needs to complete the stage3 installer.

**Comment by jacklukem** [comment]
Your MacBook5,2 not only is Penryn but also a non-APFS with legacy USB, which method do you used to install ?

Because I made many different method for group of machines.

Anyway at apple startup manager, to skip the "question mark folder" try this: https://github.com/jacklukem/USBOpenCoreAPFSloader/releases/download/3.1/USBOpenCoreAPFSloader3b.app.zip

making it with the option "Near an USB device without erasing" and selecting the USB BigSur Installer label as target, or you could use an empty USB drive, then plug it, hold alt-option key after power-on, and select your BigSur label or "macOS Installer" maybe needs to complete the stage3 installer.

**Comment by adog9712** [comment]
What is the Apple Startup Manager?

How do I use the zip file you attached?

**Comment by jacklukem** [comment]
How do you installed BigSur ?

I clearly wrote that you need a patched BaseSystem legacy usb fix and an USBopencore for those group of machines, so seems you installed without following my method.

The apple startup manager is the boot menu when you hold alt-option key after power-on : https://support.apple.com/HT202796

To use that zip you need a bootable macOS from where you can make an USB bootloader.

**Comment by adog9712** [comment]
I now understand and I am trying that now.

**Comment by adog9712** [comment]
Still not booting. Used the program from the zip to add stuff from it to my
usb and tried to install again. It’s still giving me the same error.

**Comment by jacklukem** [comment]
How you used the app from the zip?

You need a bootable macOS and from there making an external USBOpenCore through the app, then after power-on, plug the external USB bootloader and hold alt-option key for 10 seconds (https://support.apple.com/HT202796) and select the "EFI Boot" with its custom icon, then an additional menu should show the bootable APFS devices (on your non-APFS Mac), if you don't have an "EFI Boot" means you don't make properly the USBOpenCore.

Anyway how do you installed BigSur on a MacBook5,2 non-APFS Mac ?
