### ISSUE TITLE
iMac 7.1 can’t boot 

### ISSUE THREAD

**Issue by mac123456788** [jacklukem/BigSurfixes#9]
I have a iMac 7.1 and there Boots Not from the USB key. When booting from the USB key, it only shows that the Mac was restarted due to a problem.  What can I do?

Sorry for the bad English im from Germany

**Comment by jacklukem** [comment]
Minimum requirement to boot Big Sur kernel Is a Penryn Core2Duo cpu, to check if your iMac is capable booting from another macOS (example El Capitan) copy paste this:

`sysctl -a | grep machdep.cpu.brand_string ; sysctl -a | grep machdep.cpu.features`

if from output you notice SSE4.1 than your iMac could boot Big Sur , otherwise can't work.
